name: njsscan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan check
    steps:
    - uses: actions/checkout@v1
    - name: njsscan
      id: njsscan
      uses: ajinabraham/njsscan-action@v5
      with:
        args: '. --sarif --output results.sarif || true'
    - name: Upload njsscan reporte
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif